Blocklist `max_align_t` in bindgen
We observe the following test failure for i686:

    failures:
    ---- psa_crypto_binding::bindgen_test_layout_max_align_t stdout ----
    thread 'psa_crypto_binding::bindgen_test_layout_max_align_t'
    panicked at 'assertion failed: `(left == right)`
      left: `16`,
     right: `24`: Size of: max_align_t',
         .../build/psa-crypto-sys-59266dd2c6e5c562/out/shim_bindings.rs:3:22153

This type isn't needed, so we can just blocklist it from bindgen.

Signed-off-by: Joe Ellis <joe.ellis@arm.com>